services:
  main:
    build:
      dockerfile: Dockerfile
      context: src
    container_name: carbs-main
    env_file: .env.dev
    volumes:
      - ./example/config:/config
      - ./example/input:/exampleInput:ro
